### PR TITLE
Create rule-6.md

### PR DESCRIPTION
**Pull request by mhessoct**

### CODE REVIEW

**Comment by mhessoct** [comment]
Commented, I have

**Comment by landonkeller** [comment]
Logged into github on my phone at the bar, I have. Approve of these changes, i do

**Comment by LindseyJJ** [comment]
approved also have I

**Comment by mhessoct** [comment]
Leave PR open for stragglers, we shall

**Comment by clmay** [comment]
Approve as well, I do.

**Comment by clmay** [comment]
Lost have I (according to current definition of "The Group"). Penalty, I must pay. However, approvals accidentally dismissed, have I. Eager to follow the rules, I am. Therefore, re-approve Matt's PR, can we?

**Pull request merged**
